### PR TITLE
:bug: Start informers for objects that they haven't been started for yet

### LINKED ISSUE #8: bug: Failed to get object, not in cache
### Describe the bug

Replicable is here: https://github.com/kcp-dev/multicluster-provider/pull/7

But basically, if you try to get any other object, it fails as it does not exist in scopedCache, used when creating the client.

This kinda helps, but it beats the purpose of having cache in the first place. 
Image

### Steps To Reproduce

Checkout branch and run example

### Expected Behaviour

Working :) 

### Additional Context

_No response_

### PR DESCRIPTION
**Pull request by embik**
## Summary

As per the example in #7, we were unable to `List` or `Get` objects that are not watched by the controller. This change attempts to emulate what upstream controller-runtime's cache implementation does: When an informer has not been started yet, we should try to start one.

The way we start a new informer is a bit hacky due to our custom `NewInformer` logic, but this should do the trick.

## Related issue(s)

Fixes #8

## Release Notes

```release-note
NONE
```

### CODE REVIEW

File: examples/apiexport/main.go [hunk 1]
```diff
@@ -121,7 +121,14 @@ func main() {
...
 
-				log.Info("Reconciling configmap", "name", s.Name, "uuid", s.UID)
+				log.Info("Reconciling ConfigMap", "name", s.Name, "uuid", s.UID)
+
+				secrets := &corev1.SecretList{}
+				if err := client.List(ctx, secrets); err != nil {
+					return reconcile.Result{}, err
+				}
+
+				log.Info("Found Secret objects in Workspace of ConfigMap", "count", len(secrets.Items))
```
Comment (sttts) [inline examples/apiexport/main.go:131]: I don't like this here in the example. We need e2e tests.

Comment (embik) [reply examples/apiexport/main.go:131]: I agree. I can remove it from the example, I just needed a way to validate it. With the sdk changes to include a testing framework, we can write e2e tests.

Comment (embik) [reply examples/apiexport/main.go]: @sttts removed the example code changes.

**Comment by sttts** [comment]
From now on, after this PR, we need tests.

**Review by sttts — APPROVED** [review]
